import fs from "node:fs";
import vm from "node:vm";
import assert from "node:assert/strict";

const app = fs.readFileSync(new URL("../app.js", import.meta.url), "utf8");
const definitions = app.split("els.developer.addEventListener")[0];
const dummy = () => ({
  value:"platformer",textContent:"",innerHTML:"",hidden:false,disabled:false,dataset:{},style:{width:""},
  open:false,classList:{add(){},remove(){},toggle(){}},setAttribute(){},querySelector(){return dummy()},showModal(){this.open=true},close(){this.open=false},
});
const storage = new Map();
const context = {
  console,Date,Math,Number,Object,Array,String,RegExp,JSON,Intl,performance:{now:()=>0},setTimeout,clearTimeout,
  localStorage:{getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value),removeItem:key=>storage.delete(key)},
  document:{querySelector:dummy,querySelectorAll:()=>[]},window:{},confirm:()=>true,assert
};

const checks = `
assert.equal(consoles.length,24,"Le jeu doit proposer exactement 24 consoles");
assert.equal(genres.length,18,"Le jeu doit proposer 18 genres");
assert.equal(budgetTiers.length,8,"Huit budgets de production doivent exister");
assert.equal(specialistBranches.length,8,"Huit branches de spécialistes doivent exister");
assert.equal(specialists.length,40,"Chaque branche doit proposer cinq grades de spécialiste");
assert.equal(marketingPlans.length,6,"Six campagnes marketing doivent jalonner la progression");
assert.equal(studioEvents.length>=6,true,"La vie du studio doit proposer plusieurs événements");
assert.equal(awards.length,12,"Le palmarès doit comporter douze récompenses");
assert.equal(SAVE_KEY,"pixel-empire-save-v2","La version complète doit repartir sur une sauvegarde v2");
assert.equal(consoles.filter(item=>item.family==="PixelBox").length,3,"PixelBox doit avoir trois générations");
assert.equal(consoles.filter(item=>item.family==="PocketBit").length,5,"PocketBit doit avoir cinq générations");
state=initialState();
assert.equal(genres.filter(item=>genreUnlocked(item)).length,5,"Cinq genres doivent être disponibles au départ");
state.lifetimeRevenue=1e9;
assert.equal(genres.every(item=>genreUnlocked(item)),true,"Tous les genres doivent finir par se débloquer");
state=initialState();state.owned.pixelbox_1=10;
assert.equal(baseProduction(),5,"Dix PixelBox I doivent profiter du premier palier ×2");
state.money=1000;state.buyMode="max";
assert.equal(purchaseQuote(consoles[0]).count>1,true,"Le mode Max doit acheter plusieurs consoles");
assert.equal(prestigeGain({...state,runRevenue:1e6}),1,"Un million de crédits doit donner un point d’héritage");
assert.equal(prestigeGain({...state,runRevenue:4e6}),3,"L’héritage doit progresser logarithmiquement");
assert.equal(prestigeGain({...state,runRevenue:1e10}),17,"Les sommes colossales ne doivent plus produire des centaines de points d’un coup");
assert.equal(reputationMultiplier({...state,reputation:1}),1.2,"Un point d’héritage doit donner un bonus de 20 %");
assert.equal(reputationMultiplier({...state,reputation:4}),1.4,"Le bonus d’héritage doit avoir un rendement décroissant");
assert.equal(reputationMultiplier({...state,reputation:100}),3,"Cent points d’héritage doivent donner un multiplicateur ×3");
assert.equal(formatMoney(100),"100 ¤","La monnaie du jeu doit être le crédit fictif");
const trend=trendSnapshot(0);
assert.equal(trend.hot.length,3,"Trois genres doivent être en hausse");
assert.equal(trend.hot.includes(trend.cold),false,"Le genre en baisse ne doit pas être aussi en hausse");
assert.equal(budgetTiers.every((tier,index)=>index===0||tier.cost>budgetTiers[index-1].cost),true,"Les budgets doivent devenir plus coûteux");
assert.equal(budgetTiers.every((tier,index)=>index===0||tier.duration>budgetTiers[index-1].duration),true,"Les gros budgets doivent demander plus de temps");
assert.equal(budgetTiers.every((tier,index)=>index===0||tier.royalty>budgetTiers[index-1].royalty),true,"Les gros budgets doivent rapporter plus de royalties");
assert.equal(genreXpTarget(1),100,"Le niveau 2 doit demander 100 XP");
assert.equal(genreXpTarget(2),400,"Le niveau 3 doit demander 400 XP");
state=initialState();addGenreXp("platformer",budgetTiers.find(tier=>tier.id==="aaa").xp);
assert.equal(state.genreProgress.platformer.level,2,"Un jeu AAA ne doit plus faire gagner trois niveaux d’un coup");
assert.equal(state.genreProgress.platformer.xp,80,"L’expérience excédentaire doit être conservée");
state=initialState();
assert.equal(availablePlatforms().length,1,"L’ordinateur doit être la seule plateforme disponible au départ");
state.owned.pixelbox_1=1;
assert.equal(availablePlatforms().length,2,"Une console possédée doit devenir une plateforme de publication");
assert.equal(platformAffinity("pixelbox_1","platformer"),1.25,"La PixelBox doit favoriser les jeux de plateforme");
assert.equal(platformAffinity("pixelbox_1","sports"),1,"Une affinité absente ne doit pas accorder de bonus");
const singlePlatform=projectScope(budgetTiers[0],["computer"]);
const twoPlatforms=projectScope(budgetTiers[0],["computer","pixelbox_1"]);
assert.equal(twoPlatforms.cost>singlePlatform.cost,true,"Un portage doit augmenter le budget");
assert.equal(twoPlatforms.duration>singlePlatform.duration,true,"Un portage doit augmenter la durée");
const platformer=genres.find(genre=>genre.id==="platformer");
assert.equal(projectEstimate(platformer,budgetTiers[0],65,["computer","pixelbox_1"]).copies>projectEstimate(platformer,budgetTiers[0],65,["computer"]).copies,true,"Deux plateformes doivent élargir le public");
state=initialState();state.owned.pixelbox_1=4;state.upgrades=["fast_keyboard","autocomplete"];
assert.equal(clickValue(state),2+production(state)*.05,"Le clic doit combiner une base fixe et la production automatique");
state.upgrades=["autocomplete","engine_templates","assisted_programming","procedural_code"];
assert.equal(effect("clickPps",0,(a,b)=>a+b,state),.5,"Les outils manuels complets doivent incorporer 50 % de la production/s");
const testFranchise={id:"fr_test",name:"Pixel Jump",genreId:"platformer",episodes:1,xp:0,lastQuality:60};
assert.equal(franchiseLevel(testFranchise),1,"Une nouvelle franchise doit commencer au niveau 1");
assert.equal(sequelName(testFranchise),"Pixel Jump II","La première suite doit être numérotée II");
assert.equal(franchiseModifiers(testFranchise).audience,1.12,"Une suite de niveau 1 doit avoir 12 % d’audience en plus");
assert.equal(franchiseModifiers({...testFranchise,episodes:5}).fatigue,.84,"Une longue série doit subir une fatigue progressive");
assert.equal(Math.round(projectScope(budgetTiers[0],["computer"],testFranchise).cost),115,"Une suite doit coûter 15 % plus cher");
assert.equal(projectEstimate(platformer,budgetTiers[0],65,["computer"],testFranchise).copies>projectEstimate(platformer,budgetTiers[0],65,["computer"],null).copies,true,"Une franchise connue doit aider les ventes d’une suite");
state=initialState();state.lifetimeRevenue=100;state.money=10000;
assert.equal(recruitmentCandidates().length,8,"Les huit juniors doivent devenir recrutables au début");
recruitSpecialist("design_junior");
assert.equal(state.roster.includes("design_junior"),true,"Un spécialiste recruté doit rejoindre les contrats");
assert.equal(state.activeTeam.includes("design_junior"),true,"Le premier spécialiste recruté doit être activé automatiquement");
state.lifetimeRevenue=1e30;state.studioReputation=100;state.money=1e30;
assert.equal(recruitmentCandidates().some(item=>item.id==="design_confirmed"),false,"L’argent ne doit pas permettre de sauter la carrière Junior");
state.staffStats.design_junior.projects=2;
assert.equal(recruitmentCandidates().some(item=>item.id==="design_confirmed"),true,"Deux projets Junior doivent ouvrir le grade Confirmé");
recruitSpecialist("design_confirmed");activateSpecialist("design_confirmed");
assert.equal(state.activeTeam.includes("design_junior"),false,"Un nouveau profil de la même branche doit remplacer l’ancien dans l’équipe active");
assert.equal(state.roster.includes("design_junior"),true,"Le spécialiste remplacé doit rester en réserve");
assert.equal(recruitmentCandidates().some(item=>item.id==="design_expert"),false,"Un Confirmé sans expérience ne doit pas ouvrir le grade Expert");
assert.equal(teamCapacityForReputation(49),3,"La réputation faible doit conserver trois places actives");
assert.equal(teamCapacityForReputation(93),8,"Une réputation exceptionnelle doit ouvrir les huit branches");
const weakRange=projectQualityRange(platformer,budgetTiers.at(-1),["computer"],null,[],initialState());
assert.equal(weakRange.high<80,true,"Le plus gros budget seul ne doit plus garantir une excellente note");
const freshRange=projectQualityRange(platformer,budgetTiers[0],["computer"],null,[],initialState());
assert.deepEqual({low:freshRange.low,high:freshRange.high},{low:41,high:55},"Le tout premier jeu doit viser une note modeste");
state=initialState();state.lifetimeRevenue=1e4;
const targeted=marketingById("targeted");
assert.equal(projectScope(budgetTiers[0],["computer"],null,[],state,targeted).cost>projectScope(budgetTiers[0],["computer"],null,[],state).cost,true,"Le marketing doit être inclus dans l’investissement");
assert.equal(projectEstimate(platformer,budgetTiers[0],60,["computer"],null,targeted).copies>projectEstimate(platformer,budgetTiers[0],60,["computer"],null,null).copies,true,"Une campagne doit élargir l’audience de lancement");
state.awards=["first_release","press_75","players_75"];
assert.equal(awardTotal(state),3,"Les trophées doivent être additionnés");
assert.equal(marketingCost(marketingById("festival"),state),540,"La première récompense de carrière doit réduire le marketing de 10 %");
state=initialState();applyEventEffects({effects:{nextQuality:2,nextMarketing:1.5,nextDuration:.8}});
assert.equal(state.eventEffects.nextQuality,2,"Un événement doit pouvoir améliorer le prochain projet");
assert.equal(state.eventEffects.nextMarketing,1.5,"Un événement doit pouvoir renforcer la prochaine campagne");
assert.equal(state.eventEffects.nextDuration,.8,"Un événement doit pouvoir accélérer le prochain projet");
const cancellationProject={tierId:"aaa",invested:1000,startedAt:0,completesAt:1000};
assert.equal(projectCancellationQuote(cancellationProject,0).refund,650,"Une annulation immédiate doit rembourser 65 % du projet");
assert.equal(Math.round(projectCancellationQuote(cancellationProject,500).refund),425,"Le remboursement doit diminuer avec l’avancement");
assert.equal(projectCancellationQuote(cancellationProject,1000).refund,200,"Une annulation tardive ne doit rembourser que 20 % du projet");
state=initialState();state.activeProject={genreId:"platformer",tierId:"micro",platformIds:["computer"],franchiseId:null,name:"Pixel Jump",quality:60};finishProject(true);
assert.equal(state.franchises.length,1,"Un jeu original doit créer une franchise");
assert.equal(state.catalog[0].episodeNumber,1,"Le jeu fondateur doit être l’épisode 1");
assert.equal(state.catalog[0].reviews.length,3,"Chaque sortie doit recevoir trois critiques");
assert.equal(Number.isFinite(state.catalog[0].criticScore),true,"La moyenne de la presse doit être enregistrée");
assert.equal(Number.isFinite(state.studioReputation),true,"La réputation du studio doit suivre les critiques");
assert.equal(state.awards.includes("first_release"),true,"La première sortie doit remettre une récompense");
state.activeProject={genreId:"platformer",tierId:"micro",platformIds:["computer"],franchiseId:state.franchises[0].id,name:"Pixel Jump II",quality:64};finishProject(true);
assert.equal(state.franchises[0].episodes,2,"Une suite doit ajouter un épisode à sa franchise");
assert.equal(state.catalog[0].episodeNumber,2,"La suite doit être identifiée comme épisode 2");
state=initialState();updateBestGenreScore({genreId:"platformer",criticScore:91,playerScore:90,name:"Couronne Pixel"});
assert.equal(masterpieceGenreCount(state),1,"Un double score de 90 doit couronner le genre");
const finalState=initialState();
finalState.money=FINAL_PROJECT_COST;finalState.studioReputation=93;finalState.teamCapacity=8;finalState.bestGenreScores=Object.fromEntries(genres.map(genre=>[genre.id,{critic:92,player:91,mastered:true,name:"Chef-d’œuvre"}]));finalState.roster=specialistBranches.map(branch=>branch.id+"_star");finalState.activeTeam=[...finalState.roster];finalState.franchises=[1,2,3].map(index=>({id:"legend_"+index,name:"Saga "+index,genreId:"rpg",episodes:10,xp:1350,lastQuality:95}));finalState.awards=awards.map(item=>item.id);
assert.equal(finalRequirements(finalState).every(item=>item.complete),true,"Le défi final doit vérifier genres, réputation, équipe, franchises et trophées");
assert.equal(canStartFinalProject(finalState),true,"Le Projet Ultime doit s’ouvrir lorsque toutes les conditions sont remplies");
state=finalState;startFinalProject();
assert.equal(state.activeProject.isFinal,true,"Le bouton final doit lancer un projet spécial");
finishProject(true);
assert.equal(state.gameCompleted,true,"La sortie du Projet Ultime doit terminer le jeu");
assert.equal(state.catalog[0].criticScore,100,"Le Projet Ultime accompli doit recevoir 100 de la presse");
localStorage.setItem("pixel-empire-save-v1",JSON.stringify({...initialState(),money:1e30}));
localStorage.removeItem(SAVE_KEY);
assert.equal(loadState().money,0,"L’ancienne sauvegarde de prototype ne doit pas contaminer la version v2");
localStorage.removeItem(SAVE_KEY);
`;

vm.runInNewContext(`${definitions}\n${checks}`, context);
console.log("✓ Progression complète, marketing, événements, trophées et Projet Ultime validés");
